config/routes.rb
HowTo::Application.routes.draw do
  get "instructions/index"

  resources :instructions do
    resources :steps
  end

  root 'welcome#index'

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  has_many :steps
  accepts_nested_attributes_for :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :instruction
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_instruction, only: [:show, :edit, :update, :destroy]

  # GET /instructions
  # GET /instructions.json
  def index
    @instructions = Instruction.all
  end

  # GET /instructions/1
  # GET /instructions/1.json
  def show
  end

  # GET /instructions/new
  def new
    @instruction = Instruction.new
  end

  # GET /instructions/1/edit
  def edit
  end

  # POST /instructions
  # POST /instructions.json
  def create
    @instruction = Instruction.new(instruction_params)

    respond_to do |format|
      if @instruction.save
        format.html { redirect_to @instruction, notice: 'Instruction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @instruction }
      else
        format.html { render action: 'new' }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructions/1
  # PATCH/PUT /instructions/1.json
  def update
    respond_to do |format|
      if @instruction.update(instruction_params)
        format.html { redirect_to @instruction, notice: 'Instruction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1
  # DELETE /instructions/1.json
  def destroy
    @instruction.destroy
    respond_to do |format|
      format.html { redirect_to instructions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruction
      @instruction = Instruction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instruction_params
      params.require(:instruction).permit(:title, :summary)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  # before_action :set_step, only: [:show, :edit, :update, :destroy]
    before_action :load_instruction, only: [:show, :create, :edit, :update, :destroy, :new]


  # GET /steps
  # GET /steps.json
  def index
    @steps = @instruction.step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = @instruction.steps.find(params[:id])
  end

  # GET /steps/new
  def new
    # @instruction = Instruction.find(params[:instruction_id])
    # @step = Step.find(params[:step_id])
    # @step = Step.new
    @step = @instruction.steps.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    # instruction = Instruction.find(params[:instruction_id])
    # @step = @instruction.steps.new(:step_number => params[:step])
    @step = @instruction.steps.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to [@instruction, @step], notice: 'Step was successfully created.' }
        format.json { render action: 'show', status: :created, location: @step }
      else
        format.html { render action: 'new' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to steps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:step_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:step_number, :body)
    end

    def load_instruction
      @instruction=Instruction.find(params[:instruction_id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/instructions/_form.html.erb
<%= form_for(@instruction) do |f| %>
  <% if @instruction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

      <ul>
      <% @instruction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructions/edit.html.erb
<h1>Editing instruction</h1>

<%= render 'form' %>

<%= link_to 'Show', @instruction %> |
<%= link_to 'Back', instructions_path %>

app/views/instructions/index.html.erb
<h1>Listing instructions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @instructions.each do |instruction| %>
      <tr>
        <td><%= instruction.title %></td>
        <td><%= instruction.summary%></td>
        <td><%= link_to 'Show', instruction %></td>
        <td><%= link_to 'Edit', edit_instruction_path(instruction) %></td>
        <td><%= link_to 'Destroy', instruction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New instruction', new_instruction_path %>

app/views/instructions/new.html.erb
<h1>New instruction</h1>

<%= render 'form' %>

<%= link_to 'Back', instructions_path %>

app/views/instructions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <td><%= @instruction.title %></td>
  <strong>Summary:</strong>
  <td><%= @instruction.summary%></td>
</p>

<%= link_to 'Edit', edit_instruction_path(@instruction) %> |
<%= link_to 'Back', instructions_path %>
<%= link_to 'Add Step', new_instruction_step_path(@instruction, @step) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowTo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for([@instruction, @step]) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :step_number %><br>
    <%= f.text_field :step_number %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <thead>
    <tr>
      <th>Step</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.step %></td>
        <td><%= step.body %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Step:</strong>
  <%= @step.step_number %>
</p>

<p>
  <strong>Body:</strong>
  <%= @step.body %>
</p>

<%= link_to 'Edit', edit_instruction_path(@step) %>
<%= link_to 'Delete', method: :destroy%>

app/views/welcome/index.html.erb
<h1>hi</h1>